// GENERATED by scripts/gen-toolchain-hash.mjs — do not edit by hand.
// The §4.4 toolchainHash of the installed @lofcz/transpiler (= the
// published tarball). Regenerated on every build (prebuild). The deploy asserts
// this equals the hash the CLI stamps into artifact indexes (G2-8).

export const EMBEDDED_TOOLCHAIN_HASH = 'da6b877141549e8b13e62b725346875d6a15d923eba63d14303b704ec421546b';
