// GENERATED by scripts/gen-toolchain-hash.mjs — do not edit by hand.
// The §4.4 toolchainHash of the installed @lofcz/transpiler (= the
// published tarball). Regenerated on every build (prebuild). The deploy asserts
// this equals the hash the CLI stamps into artifact indexes (G2-8).

export const EMBEDDED_TOOLCHAIN_HASH = '584ca0d9400769152876769397d7b72b0f6b2f033f67434eac5496983a7c0cbd';
